export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const GET_ARTICLES_BEGIN = "GET_ARTICLES_BEGIN";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";

export const CREATE_ARTICLE_BEGIN = "CREATE_ARTICLE_BEGIN";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_ERROR = "CREATE_ARTICLE_ERROR";

export const EDIT_ARTICLE_BEGIN = "EDIT_ARTICLE_BEGIN";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";
export const EDIT_ARTICLE_ERROR = "EDIT_ARTICLE_ERROR";

export const DELETE_ARTICLE_BEGIN = "DELETE_ARTICLE_BEGIN";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";

export const TOGGLE_FLAG_BEGIN = "TOGGLE_FLAG_BEGIN";
export const TOGGLE_FLAG_SUCCESS = "TOGGLE_FLAG_SUCCESS";

export const TOGGLE_PUBLISH_BEGIN = "TOGGLE_PUBLISH_BEGIN";
export const TOGGLE_PUBLISH_SUCCESS = "TOGGLE_PUBLISH_SUCCESS";

export const CHANGE_STATUS = "CHANGE_STATUS";

export const SELECT_TAG = "SELECT_TAG";

export const CHANGE_SEARCH_TYPE = "CHANGE_SEARCH_TYPE";

export const CHANGE_SEARCH_FLAG = "CHANGE_SEARCH_FLAG";

export const LOGOUT_USER = "LOGOUT_USER";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";
export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const TOGGLE_ADD_ITEMS = "TOGGLE_ADD_ITEMS";

export const SET_EDIT_ARTICLE = "SET_EDIT_ARTICLE";